Read Arp UI reg and autostart service when Profile Id is set and UI=false
nextdns/windows pull request #29
Opened 2022-06-23 15:25 UTC by Delaire

Update service so we can read the ARP and UI values in the reg
Handle OnStart event to check to see we have Profile ID and UI=False to autostart service without having to use client app

2022-06-23 15:43 UTC, rs commented on service/main.go
> +				//then try to start service
nit: can you add a space between // and the comment, make it one line comment and add capital and period. Sorry I'm a bit OCD on this :)

2022-06-23 15:45 UTC, rs commented on service/main.go
> +					s.log.Info(fmt.Sprintf("Configuration found : %v", stg.Configuration))
nit: no space before ":".

2022-06-23 15:46 UTC, rs commented on service/settings/settings.go
> +	if v, ok := m["ARP"].(string); ok {
Why would it be encoded as string instead of bool?

2022-06-23 15:47 UTC, rs commented on service/settings/settings.go
> +		}
```
s.ARP = v == "true"
```

2022-06-24 14:41 UTC, Delaire commented on service/main.go
> +				//then try to start service
no worries

2022-06-24 14:50 UTC, Delaire commented on service/settings/settings.go
> +	if v, ok := m["ARP"].(string); ok {
We don't have the option to create a regkey with a bool value:
![Uploading image.png…]()
I can save it as a Binary value? but the issue will be the same at some point we are going to need to convert it =(

2022-06-24 20:00 UTC, rs commented on service/main.go
> +				// Check that user in in no UI mode and has profile id set to start service
in in -> is in?

2022-06-27 19:07 UTC, rs commented on service/settings/settings.go
> +		//s.ARP = v == "true"
```suggestion
```

2022-06-27 19:07 UTC, rs commented on service/settings/settings.go
> +	if v, ok := m["ARP"].(uint64); ok {
```suggestion
	if v, ok := m["ARP"].(bool); ok {
```

2022-06-27 19:07 UTC, rs commented on service/settings/settings.go
> +	if v, ok := m["UI"].(uint64); ok {
```suggestion
	if v, ok := m["UI"].(bool); ok {
```

2022-06-27 19:07 UTC, rs commented on service/settings/settings.go
> +	if v, ok := m["ARP"].(uint64); ok {
From the UI, you need to send Booleans.

2022-06-27 19:07 UTC, rs commented on service/main.go
> +	fmt.Printf("ARP : %s\n", s.ARP)
```suggestion
	fmt.Printf("UI : %v\n", s.UI)
	fmt.Printf("ARP : %v\n", s.ARP)
```

2022-06-27 19:07 UTC, rs commented on service/settings/registry.go
> +
```suggestion
```

2022-06-27 19:07 UTC, rs commented on service/settings/registry.go
> +
No empty line between func call and error check.

2022-06-27 19:07 UTC, rs commented on service/main.go
> +	showConfigInfo := flag.Bool("configInfo", false, "Show configuration information")
This will only show the registry configuration, not the UI ones. The name is confusing. Perhaps it's better to just print the configuration in the logs.

2022-06-29 05:52 UTC, Delaire commented on service/main.go
> +	settings.FromRegistry()
yes sorry

2022-06-29 05:56 UTC, Delaire commented on service/main.go
> +	showConfigInfo := flag.Bool("configInfo", false, "Show configuration information")
I agree, should I make this a bool like debug and print the info in the logs if requested?

2022-06-29 09:45 UTC, rs commented on service/main.go
> +	showConfigInfo := flag.Bool("configInfo", false, "Show configuration information")
Why not always printing it in the logs?

2022-07-03 17:37 UTC, rs commented on nsis/NextDNSSetup.nsi
> +	CreateShortCut "$SMPROGRAMS\Startup\${MUI_PRODUCT}.lnk" "$INSTDIR\${MUI_PRODUCT}Service.exe" "-service start"
Why do you need this? The service is already installed in the other section and should start with the system.

2022-07-03 17:37 UTC, rs commented on nsis/NextDNSSetup.nsi
> +	WriteRegStr HKCU "Software\${MUI_PRODUCT}" "" $INSTDIR
Please make sure you don't mix tab and spaces for indentation in this file.

2022-07-06 15:51 UTC, Delaire commented on nsis/NextDNSSetup.nsi
> +	CreateShortCut "$SMPROGRAMS\Startup\${MUI_PRODUCT}.lnk" "$INSTDIR\${MUI_PRODUCT}Service.exe" "-service start"
You are correct, I tested again and I dont need this part of the code anymore ill clean this up

2022-07-06 15:51 UTC, Delaire commented on nsis/NextDNSSetup.nsi
> +	CreateShortCut "$SMPROGRAMS\Startup\${MUI_PRODUCT}.lnk" "$INSTDIR\${MUI_PRODUCT}Service.exe" "-service start"
You are correct, I tested again and I dont need this part of the code anymore ill clean this up

2022-07-06 16:02 UTC, Delaire commented on nsis/NextDNSSetup.nsi
> +	WriteRegStr HKCU "Software\${MUI_PRODUCT}" "" $INSTDIR
I have changed all my tabs to 4 spaces

2022-07-10 14:05 UTC, Delaire commented
I believe this branch can be merged into the main?

2022-07-11 20:16 UTC, rs requested changes

2022-07-11 20:16 UTC, rs commented on nsis/NextDNSSetup.nsi
> +    WriteRegStr HKCU "Software\${MUI_PRODUCT}" "" $INSTDIR
As this is in both condition, shouldn't we just do outside the condition above?

2022-07-11 20:16 UTC, rs commented on nsis/NextDNSSetup.nsi
> +    # Start menu
```suggestion
    ; Start menu
```

2022-07-11 20:16 UTC, rs commented on nsis/NextDNSSetup.nsi
> +  #are we on x64 system , read x64 reg
```suggestion
  ; On x64 system, read x64 reg
```

2022-07-11 20:16 UTC, rs commented on nsis/NextDNSSetup.nsi
> +    WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${MUI_PRODUCT}" "NoRepair" 1
@Delaire why do we write these if ARP is 0?

2022-07-12 06:17 UTC, Delaire commented on nsis/NextDNSSetup.nsi
> +    WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${MUI_PRODUCT}" "NoRepair" 1
this PR needs to be merged after the nsi PR, I should not have split the PR in 2 makes for more confusion, do you want me to merge both PR?

2022-07-12 07:29 UTC, rs commented on nsis/NextDNSSetup.nsi
> +    WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${MUI_PRODUCT}" "NoRepair" 1
Yes please

2022-07-13 10:58 UTC, closed without merging