msi build with PROFILE/ ARP/ UI / SKIP
nextdns/windows pull request #30
Opened 2022-07-03 05:19 UTC by Delaire

Adding a first draft on building an MSI using Advanced Installer, can handle the properties PROFILE/ ARP/ UI/ SKIP.

The saving of the properties was moved outside of the aip project so that it can be move easily updated, it is located in the powershell script called InstallProperties.ps1

Examples:
msiexec.exe /i "NextDNS.msi" /qn PROFILE=newKey01 UI=no ARP=no
msiexec.exe /i "NextDNS.msi" /qn PROFILE=newKey01 UI=false ARP=true
msiexec.exe /i "NextDNS.msi" /qn PROFILE=newKey01 UI=false

With SKIP
msiexec.exe /i "NextDNS.msi" /qn PROFILE=newKey01 SKIP=UI,ARP

UI and ARP possible options : 
No/FALSE are not case sensitive  (N/F can be added if needed?)
Yes/TRUE are not case sensitive (T/Y can be added if needed?)

SKIP possible options:
UI / ARP are not case sensitive

2022-07-03 17:43 UTC, rs commented
Can you please add the building of the msi to the main build script?

2022-07-03 17:43 UTC, rs commented on msi/NextDNS.aip
> +    <ROW Property="ARPCONTACT" Value="team@nextdns.io"/>
Are contact and phone properties required?

2022-07-03 17:43 UTC, rs commented on msi/install_examples.txt
> +msiexec.exe /i "NextDNS.msi" /qn PROFILE=newKey01 UI=no ARP=no
Content of this file should be moved to the README

2022-07-04 05:34 UTC, Delaire commented on msi/NextDNS.aip
> +    <ROW Property="ARPCONTACT" Value="team@nextdns.io"/>
No it is not, ill remove.
![image](https://user-images.githubusercontent.com/6408479/177087808-856f9eb7-f1b2-4f92-aabf-26919a69c67e.png)

2022-07-04 09:34 UTC, rs commented on msi/NextDNS.aip
> +    <ROW Property="ARPHELPLINK" Value="https://nextdns.io/"/>
This one is https://help.nextdns.io

2022-07-09 13:22 UTC, Delaire commented
> Can you please add the building of the msi to the main build script?

I have update the build.bat file with advanced installer cli to build the msi

2022-07-09 15:16 UTC, rs requested changes

2022-07-09 15:16 UTC, rs commented on build.bat
> +	set "PathExe="
Mixed identation

2022-07-09 15:16 UTC, rs commented on msi/PowerShellScriptInline/InstallProperties.ps1
> +		New-ItemProperty -Path $registryPath -Name "UI" -Value 0 -PropertyType DWord -Force | Out-Null
If only UI, make sure ARP is removed

2022-07-09 15:16 UTC, rs commented on msi/PowerShellScriptInline/InstallProperties.ps1
> +		New-ItemProperty -Path $registryPath -Name "ARP" -Value 0 -PropertyType DWord -Force | Out-Null
If only ARP, make sure UI is removed

2022-07-09 15:16 UTC, rs commented on msi/PowerShellScriptInline/InstallProperties.ps1
> +{
Can we detect if SKIP is provided with no value (as opposed to no provided at all)? If SKIP is provided with no value, it should be a value to reset all skips (remove the regs).

2022-07-09 15:16 UTC, rs commented on README.md
> +```msiexec.exe /i "NextDNS.msi" /qn PROFILE=newKey01 SKIP=UI_AND_ARP```
Please support `UI,ARP` and only that (no `_AND_` or `/`).

2022-07-09 15:16 UTC, rs commented on msi/PowerShellScriptInline/InstallProperties.ps1
> +	IF($propSkipValue.ToUpper() -contains "UI_AND_ARP" -or $propSkipValue.ToUpper() -contains "ARP_AND_UI"	-or $propSkipValue.ToUpper() -contains "UI/ARP" -or $propSkipValue.ToUpper() -contains "ARP/UI"
What about splitting the string on `,` and then test for the presence of each supported flag?

2022-07-11 20:23 UTC, rs commented on README.md
>  * Install [NSIS](https://nsis.sourceforge.io/Download)
Don't we need to install something to build the MSI?

2022-07-13 12:46 UTC, Delaire commented
Ill redo a full check of the nsis install / uninstall , with and with out reg keys before the end of the week so that we are ok on what has been done

2022-07-29 08:58 UTC, Delaire commented
I have tested the following install options for exe and msi, do you think I need to test something else?
![image](https://user-images.githubusercontent.com/6408479/181723568-f198b8fe-da2c-4b32-931e-a2f4c65e021b.png)

2022-09-19 15:07 UTC, merged